# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf077cdd162d6641b7d53140d55db6c61b2fabcfd24b9a39643197b0a43e0da0729caa10b26de6ca53ef0d10acfc4ef557d3b865d8207472f610040b6010260

test:
  secret_key_base: 07ab6302bf02ce09a7250333e8bb4e9f2af9d7d1f177fa9840181bc56c4e21247b922e6d1b288816a68b20bb912388426f392627918fae82edc451b9ffcc18e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
